# Generated by Django 4.1.2 on 2022-11-07 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('DIRECTOR', 'Director'), ('ADMIN', 'Admin'), ('TEACHER', 'Teacher'), ('CLIENT', 'Client')], default='CLIENT', max_length=30),
        ),
    ]
