# Generated by Django 3.2.5 on 2022-11-10 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_auto_20221108_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('DIRECTOR', 'Director'), ('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('TEACHER', 'Teacher'), ('STUDENT', 'Student')], default='STUDENT', max_length=30),
        ),
    ]
