# Generated by Django 3.2.5 on 2022-11-16 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0008_auto_20221114_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='days_between_lessons',
            field=models.IntegerField(choices=[(7, 'Every week'), (14, 'Every 2 weeks')], default=7),
        ),
        migrations.AlterField(
            model_name='request',
            name='duration',
            field=models.IntegerField(choices=[(30, '30 minutes'), (45, '45 minutes'), (60, '60 minutes')], default=60),
        ),
        migrations.AlterField(
            model_name='request',
            name='fulfilled',
            field=models.BooleanField(default=False),
        ),
    ]
