# Generated by Django 3.2.5 on 2022-11-17 20:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0009_auto_20221116_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='days_between_lessons',
            field=models.IntegerField(choices=[(7, 'Every week'), (14, 'Every 2 weeks')], default=7),
        ),
        migrations.AlterField(
            model_name='booking',
            name='duration',
            field=models.IntegerField(choices=[(30, '30 minutes'), (45, '45 minutes'), (60, '60 minutes')], default=60),
        ),
        migrations.AlterField(
            model_name='booking',
            name='lessons',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='request',
            name='lessons',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
