# Generated by Django 3.2.5 on 2022-11-17 21:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0011_auto_20221117_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 17, 21, 39, 45, 872808)),
        ),
    ]
