# Generated by Django 3.2.5 on 2022-11-17 21:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0013_alter_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 17, 21, 40, 49, 878765, tzinfo=utc)),
        ),
    ]
