# Generated by Django 4.1.3 on 2022-11-22 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0018_auto_20221120_1539'),
        ('lessons', '0018_transfer'),
    ]

    operations = [
    ]
