# Generated by Django 4.1.3 on 2022-11-23 13:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0019_merge_0018_auto_20221120_1539_0018_transfer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_ref', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('due_by_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19, validators=[django.core.validators.MinValueValidator(1)])),
                ('refund', models.BooleanField(default=False)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lessons.booking')),
            ],
        ),
        migrations.DeleteModel(
            name='Transfer',
        ),
    ]
